# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-11 22:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^d{9,15}$')])),
                ('total_amount_due', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('next_payment_date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
