# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-11 23:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='next_payment_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='total_amount_due',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
