# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-10 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_reminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='next_payment_date',
            new_name='first_payment_date',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='payment_amount',
            new_name='monthly_payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Client'),
        ),
    ]
