# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-12 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200112_1742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
