# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-13 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_delete_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_payment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
