# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-22 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200112_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='admin_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
